---
title: "NHL_Standing_Analysis"
author: "Eamon Devlin"
date: "11/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(pwr)
library(knitr)
library(kableExtra)
library(plotly)
library(extrafont)
library(ggrepel)
library(dplyr)
library(tinytex)
library(RColorBrewer)
library(effsize)
```

Read in data

```{r}

team_stats_2018_11_10 <- read_csv("team_stats_2018-11-10.csv")

```

### 2017-2018 Analysis (Ranks)

First mode of analysis is looking at the 2017-2018 season




```{r}
# First create a 2017 - 2018 subset

season_2017_2018 <- select(team_stats_2018_11_10, Team:PDO) %>% 
  filter(Season == "2017-2018") %>% 
  mutate(
    conference = case_when(
    Team == "ANA" ~ "west",
    Team == "ARI" ~ "west",
    Team == "BOS" ~ "east",
    Team == "BUF" ~ "east", 
    Team == "CAR" ~ "east",
    Team == "CBJ" ~ "east",
    Team == "CGY" ~ "west",
    Team == "CHI" ~ "west",
    Team == "COL" ~ "west",
    Team == "DAL" ~ "west",
    Team == "DET" ~ "east",
    Team == "EDM" ~ "west",
    Team == "FLA" ~ "east",
    Team == "L.A" ~ "west",
    Team == "MIN" ~ "west",
    Team == "MTL" ~ "east",
    Team == "N.J" ~ "east",
    Team == "NSH" ~ "east",
    Team == "NYI" ~ "east",
    Team == "NYR" ~ "east",
    Team == "OTT" ~ "east",
    Team == "PHI" ~ "east",
    Team == "PIT" ~ "east",
    Team == "S.J" ~ "west",
    Team == "STL" ~ "west",
    Team == "T.B" ~ "east",
    Team == "TOR" ~ "east",
    Team == "VAN" ~ "west",
    Team == "VGK" ~ "west",
    Team == "WPG" ~ "west",
    Team == "WSH" ~ "east"
    )) 

conf_2017_2018 <- group_by(season_2017_2018, conference)

# conf_hist <- ggplot(conf_2017_2018, aes())

```

Basic histogram for GF and GA per 60 minutes

```{r}
gf_hist_2017_2018 <- ggplot(season_2017_2018, aes(`GF/60`)) +
  geom_histogram(bins = 7, aes(fill = conference)) +
                 #  "darkblue", colour = "dodgerblue") +
  labs(x = "Goals For Per 60 Minutes", y = "Frequency") +
  theme_classic() +
  scale_y_continuous(expand = c(0,0))  # +
  # facet_wrap(~conference)  #, scales = "free")

gf_hist_2017_2018


#  Perform Rank Test
east_2017_2018 <- season_2017_2018 %>% 
  filter(conference == "east")
west_2017_2018 <- season_2017_2018 %>% 
  filter(conference == "west")

rank_gf_2017_2018 <- wilcox.test(west_2017_2018$`GF/60`,east_2017_2018$`GF/60`, paired = FALSE)

rank_gf_2017_2018

ttest_gf_2017_2018 <- t.test(west_2017_2018$`GF/60`,east_2017_2018$`GF/60`)


```






